[tool.poetry]
name = "word-chain-bot-indently"
version = "4.3.1"
description = "Word Chain Discord bot, born from the Indently Discord server!"
authors = ["Wrichik Basu <56736644+WrichikBasu@users.noreply.github.com>",
           "Sir Lefti <62506842+SirLefti@users.noreply.github.com"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
"discord.py" = "^2.3.2"
python-dotenv = "^1.0.1"
requests-futures = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
